modLoader="javafml"
loaderVersion="[3,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}"
description="${description}"
[[mixins]]
config="chunky.mixins.json"
[[dependencies.chunky]]
   modId="neoforge"
   type="required"
   versionRange="[21.11.0-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunky]]
   modId="minecraft"
   type="required"
   versionRange="[1.21.11,1.22)"
   ordering="NONE"
   side="BOTH"
